rm -f ecaltemplates_popcon_UltraLegacy2017_calib.db

conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_297046_297101.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 294645
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_297113_297316.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 297113
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_297359_297505.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 297359
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_297557_297723.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 297557
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_298809_299067.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 298809
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_299096_299329.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 299096
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_299368_299450.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 299368
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_299477_299650.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 299477
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_300079_300124.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 300079
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_300155_300401.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 300155
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_300459_300742.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 300459
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_300777_301165.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 300777
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_301330_301480.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 301330
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_301519_301914.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 301519
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_301941_302044.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 301941
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_302131_302280.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 302131
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_302322_302479.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 302215
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_302484_302555.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 302484
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_302563_302678.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 302563
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_303817_303832.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 303817
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_303838_304062.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 303838
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_304119_304354.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 304119
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_304366_304655.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 304366
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_304661_304797.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 304661
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_305040_305114.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 305040
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_305178_305252.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 305178
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_305310_305518.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 305310
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_305586_305842.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 305586
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_305902_306126.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 305902
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_306134_306462.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 306134
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_306896_307082.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_UltraLegacy2017_calib.db -t EcalPulseShapes_data -b 306828


echo "===> Now checking the contents..."
conddb --db ecaltemplates_popcon_UltraLegacy2017_calib.db list EcalPulseShapes_data
