rm -f ecaltemplates_popcon_Ultimate2016_calib.db
  
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_271983_272818.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 271865
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_273301_273590.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 272818
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_274080_274344.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 274080
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_274958_275281.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 274958
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_275282_275376.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 275282
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_275656_275847.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 275656
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_275886_276097.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 275886
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_276282_276502.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 276282
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_276525_276659.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 276525
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_276775_276811.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 276775
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_278167_278175.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 277932
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_278969_278976.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 278346
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_279115_279116.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 278977
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_279653_279658.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 279474
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_279715_279716.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 279715
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_279841_279841.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 279717
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_279993_280024.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 279993
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_280327_280364.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 280327
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_281616_282092.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 281010
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_282408_282712.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 282408
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_282730_282814.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 282730
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_283171_283835.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 283171
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_runs_283863_284035.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_Ultimate2016_calib.db -t EcalPulseShapes_data -b 283863

echo "===> Now checking the contents..."
conddb --db ecaltemplates_popcon_Ultimate2016_calib.db list EcalPulseShapes_data
