# ---- templates ----
#conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/public/ecal/pulseshapes_db/ecaltemplates_popcon_data_Run2015C_lowPU.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_weekly_best.db -t EcalPulseShapes_data -b 248036
#conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/ecal/ecalreco/multifit/studies_25ns/CMSSW_7_4_15_patch1/src/EcalReconstruction/dbscripts/ecaltemplates_popcon_runs_257616_258600.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_weekly_best.db -t EcalPulseShapes_data -b 257616
#conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/ecal/ecalreco/multifit/studies_25ns/CMSSW_7_4_15_patch1/src/EcalReconstruction/dbscripts/ecaltemplates_popcon_runs_258601_999999.db -i EcalPulseShapes_data -c sqlite_file:ecaltemplates_popcon_weekly_best.db -t EcalPulseShapes_data -b 258601 

# ---- covariances ----
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/ecal/ecalreco/multifit/studies_25ns/CMSSW_7_4_15_patch1/src/EcalReconstruction/dbscripts/ecalcovariances_popcon_runs_248036_257615.db -i EcalPulseCovariances_data -c sqlite_file:ecalcovariances_popcon_weekly_best.db -t EcalPulseCovariances_data -b 248036
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/ecal/ecalreco/multifit/studies_25ns/CMSSW_7_4_15_patch1/src/EcalReconstruction/dbscripts/ecalcovariances_popcon_runs_257616_258600.db -i EcalPulseCovariances_data -c sqlite_file:ecalcovariances_popcon_weekly_best.db -t EcalPulseCovariances_data -b 257616
conddb_import -f sqlite_file:/afs/cern.ch/work/e/emanuele/ecal/ecalreco/multifit/studies_25ns/CMSSW_7_4_15_patch1/src/EcalReconstruction/dbscripts/ecalcovariances_popcon_runs_258601_999999.db -i EcalPulseCovariances_data -c sqlite_file:ecalcovariances_popcon_weekly_best.db -t EcalPulseCovariances_data -b 258601
